### ISSUE TITLE
RuntimeError: CUDA out of memory.

### ISSUE THREAD

**Issue by ahmedamein100** [tqbl/dcase2020_task5#6]
HI , I got some issue with shortage of meomry but i solve it by decreasing the batch size to 16 (1050 ti 4GB), it was solve for the training set only , but with the validation set it got me the same error as shown in this photo :
![Screenshot (5)](https://user-images.githubusercontent.com/61803286/166921119-11878b95-ea64-42c0-bc58-818e8d5ee712.png)

i decresed the batch size again to 8 , but it got me the same error for the validation test , and the weird thing that i got the same message with the same numbers that i have got with batch size 16 so i was confused how is batch size 16 and 8 have the same error message with the same numbers exactly.

i was thinking that it is not using the gpu so i downloaded the cudtoolkit 10.1 and i update my nvidia drive and i write the command 
"nvcc --version" and this was the result : 
![Screenshot (6)](https://user-images.githubusercontent.com/61803286/166922269-44ed5506-10ac-411d-b521-7f4f10bb3e0b.png)
 so i think everthing is right.

i download all requirments as you asked and pytorch version 1.4.0 cuda 10.1 and am using python 3.6.14.

Let me show you the error trace back(Highlighted one) : 
![Screenshot (7)](https://user-images.githubusercontent.com/61803286/166922657-162c8e38-8496-49b7-aacd-e04257279c28.png)

**Comment by tqbl** [comment]
Apologies for missing this thread. I'm going to close it as it's been several months.
